// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag/v2"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "components": {
        "schemas": {
            "adminapi.ConfigResponse": {
                "properties": {
                    "defaults": {
                        "$ref": "#/components/schemas/policy.Defaults"
                    },
                    "facts": {
                        "items": {
                            "$ref": "#/components/schemas/facts.Spec"
                        },
                        "type": "array",
                        "uniqueItems": false
                    },
                    "groups": {
                        "items": {
                            "$ref": "#/components/schemas/adminapi.GroupViewElement"
                        },
                        "type": "array",
                        "uniqueItems": false
                    },
                    "logging": {
                        "$ref": "#/components/schemas/policy.Logging"
                    }
                },
                "type": "object"
            },
            "adminapi.DefaultsRequest": {
                "properties": {
                    "action": {
                        "enum": [
                            "allow",
                            "deny"
                        ],
                        "example": "deny",
                        "type": "string"
                    },
                    "allowOnError": {
                        "type": "boolean"
                    },
                    "denyBody": {
                        "example": "Forbidden",
                        "type": "string"
                    },
                    "denyStatus": {
                        "example": 403,
                        "type": "integer"
                    },
                    "maxBodyBytes": {
                        "example": "1MiB",
                        "type": "string"
                    }
                },
                "type": "object"
            },
            "adminapi.ErrorResponse": {
                "properties": {
                    "error": {
                        "description": "Error is a short, human-readable explanation.",
                        "example": "rebuild failed: group \"x\": rules must not be empty",
                        "type": "string"
                    }
                },
                "type": "object"
            },
            "adminapi.FactFileSpec": {
                "properties": {
                    "path": {
                        "example": "/etc/policy/lists/cidrs.json",
                        "type": "string"
                    }
                },
                "type": "object"
            },
            "adminapi.FactRequest": {
                "properties": {
                    "file": {
                        "$ref": "#/components/schemas/adminapi.FactFileSpec"
                    },
                    "method": {
                        "enum": [
                            "value",
                            "file",
                            "url"
                        ],
                        "example": "url",
                        "type": "string"
                    },
                    "name": {
                        "example": "chatgptFeed",
                        "type": "string"
                    },
                    "url": {
                        "$ref": "#/components/schemas/adminapi.FactURLSpec"
                    },
                    "value": {
                        "type": "object"
                    }
                },
                "type": "object"
            },
            "adminapi.FactURLSpec": {
                "properties": {
                    "address": {
                        "example": "https://openai.com/chatgpt-actions.json",
                        "type": "string"
                    },
                    "headers": {
                        "additionalProperties": {
                            "type": "string"
                        },
                        "type": "object"
                    },
                    "interval": {
                        "example": "10m",
                        "type": "string"
                    },
                    "timeout": {
                        "example": "15s",
                        "type": "string"
                    }
                },
                "type": "object"
            },
            "adminapi.GroupRequest": {
                "properties": {
                    "action": {
                        "enum": [
                            "allow",
                            "deny"
                        ],
                        "example": "deny",
                        "type": "string"
                    },
                    "description": {
                        "example": "Block a residential ASN at request time",
                        "type": "string"
                    },
                    "match": {
                        "type": "string"
                    },
                    "mode": {
                        "enum": [
                            "firstMatch",
                            "all"
                        ],
                        "example": "firstMatch",
                        "type": "string"
                    },
                    "name": {
                        "example": "api-block-residential",
                        "type": "string"
                    },
                    "priority": {
                        "example": -100,
                        "type": "integer"
                    },
                    "rules": {
                        "items": {
                            "$ref": "#/components/schemas/adminapi.RuleRequest"
                        },
                        "type": "array",
                        "uniqueItems": false
                    }
                },
                "type": "object"
            },
            "adminapi.GroupViewElement": {
                "properties": {
                    "action": {
                        "type": "string"
                    },
                    "description": {
                        "type": "string"
                    },
                    "match": {
                        "type": "string"
                    },
                    "mode": {
                        "type": "string"
                    },
                    "name": {
                        "type": "string"
                    },
                    "priority": {
                        "type": "integer"
                    },
                    "rules": {
                        "items": {
                            "$ref": "#/components/schemas/adminapi.RuleRequest"
                        },
                        "type": "array",
                        "uniqueItems": false
                    },
                    "source": {
                        "enum": [
                            "yaml",
                            "api"
                        ],
                        "example": "yaml",
                        "type": "string"
                    }
                },
                "type": "object"
            },
            "adminapi.ItemListResponse": {
                "properties": {
                    "items": {
                        "items": {
                            "$ref": "#/components/schemas/adminapi.ItemResponse"
                        },
                        "type": "array",
                        "uniqueItems": false
                    }
                },
                "type": "object"
            },
            "adminapi.ItemResponse": {
                "properties": {
                    "name": {
                        "description": "Name is the entry key (e.g. group name, fact name).",
                        "example": "api-block-residential",
                        "type": "string"
                    },
                    "payload": {
                        "description": "Payload is the JSON payload exactly as it would appear inside\nthe YAML policy (decoded into a generic object).",
                        "type": "object"
                    },
                    "section": {
                        "description": "Section is the parent collection (\"groups\" or \"facts\").",
                        "example": "groups",
                        "type": "string"
                    },
                    "stamp": {
                        "$ref": "#/components/schemas/crdt.Stamp"
                    },
                    "tombstone": {
                        "description": "Tombstone is true when the entry is a deletion marker.",
                        "example": false,
                        "type": "boolean"
                    }
                },
                "type": "object"
            },
            "adminapi.LoggingRequest": {
                "properties": {
                    "excludeHeaders": {
                        "items": {
                            "type": "string"
                        },
                        "type": "array",
                        "uniqueItems": false
                    },
                    "format": {
                        "enum": [
                            "json",
                            "console"
                        ],
                        "example": "json",
                        "type": "string"
                    },
                    "level": {
                        "enum": [
                            "debug",
                            "info",
                            "warn",
                            "error"
                        ],
                        "example": "info",
                        "type": "string"
                    },
                    "logBody": {
                        "type": "boolean"
                    },
                    "redactHeaders": {
                        "items": {
                            "type": "string"
                        },
                        "type": "array",
                        "uniqueItems": false
                    },
                    "redactQueryParams": {
                        "items": {
                            "type": "string"
                        },
                        "type": "array",
                        "uniqueItems": false
                    },
                    "redactReveal": {
                        "example": 6,
                        "type": "integer"
                    }
                },
                "type": "object"
            },
            "adminapi.QuarantineListResponse": {
                "properties": {
                    "items": {
                        "items": {
                            "$ref": "#/components/schemas/quarantine.Entry"
                        },
                        "type": "array",
                        "uniqueItems": false
                    }
                },
                "type": "object"
            },
            "adminapi.RegisterResponse": {
                "properties": {
                    "payload": {
                        "type": "object"
                    },
                    "section": {
                        "example": "defaults",
                        "type": "string"
                    },
                    "stamp": {
                        "$ref": "#/components/schemas/crdt.Stamp"
                    }
                },
                "type": "object"
            },
            "adminapi.RuleRequest": {
                "properties": {
                    "action": {
                        "enum": [
                            "allow",
                            "deny"
                        ],
                        "example": "deny",
                        "type": "string"
                    },
                    "description": {
                        "type": "string"
                    },
                    "dryRun": {
                        "type": "boolean"
                    },
                    "fallthrough": {
                        "enum": [
                            "next",
                            "allow",
                            "deny"
                        ],
                        "example": "next",
                        "type": "string"
                    },
                    "match": {
                        "example": "request.remoteIp == \"203.0.113.5\"",
                        "type": "string"
                    },
                    "name": {
                        "example": "block-bad-ip",
                        "type": "string"
                    }
                },
                "type": "object"
            },
            "crdt.Stamp": {
                "description": "Stamp is the LWW timestamp that resolved the last write.",
                "properties": {
                    "node": {
                        "type": "string"
                    },
                    "ts": {
                        "type": "integer"
                    }
                },
                "type": "object"
            },
            "facts.Spec": {
                "type": "object"
            },
            "policy.Defaults": {
                "type": "object"
            },
            "policy.Logging": {
                "type": "object"
            },
            "quarantine.Entry": {
                "properties": {
                    "key": {
                        "type": "string"
                    },
                    "lastRetry": {
                        "type": "string"
                    },
                    "reason": {
                        "type": "string"
                    },
                    "retryCount": {
                        "type": "integer"
                    },
                    "section": {
                        "type": "string"
                    },
                    "since": {
                        "type": "string"
                    }
                },
                "type": "object"
            }
        },
        "securitySchemes": {
            "BearerAuth": {
                "description": "Send 'Bearer \u003ctoken\u003e'. The token is the contents of --admin-token-file on the server.",
                "in": "header",
                "name": "Authorization",
                "type": "apiKey"
            }
        }
    },
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "version": "{{.Version}}"
    },
    "externalDocs": {
        "description": "",
        "url": ""
    },
    "paths": {
        "/api/v1/config": {
            "get": {
                "description": "Returns the policy the engine would evaluate right now (YAML floor + CRDT overrides), with sources annotated per group.",
                "responses": {
                    "200": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/adminapi.ConfigResponse"
                                }
                            }
                        },
                        "description": "OK"
                    },
                    "401": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/adminapi.ErrorResponse"
                                }
                            }
                        },
                        "description": "Unauthorized"
                    },
                    "500": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/adminapi.ErrorResponse"
                                }
                            }
                        },
                        "description": "merge or compile failed"
                    }
                },
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "summary": "Effective compiled policy",
                "tags": [
                    "config"
                ]
            }
        },
        "/api/v1/defaults": {
            "delete": {
                "description": "After this call the YAML defaults are the effective ones again.",
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "401": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/adminapi.ErrorResponse"
                                }
                            }
                        },
                        "description": "Unauthorized"
                    }
                },
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "summary": "Clear the defaults overlay",
                "tags": [
                    "defaults"
                ]
            },
            "get": {
                "description": "Returns 404 when no admin override is set; in that case the YAML defaults are in effect.",
                "responses": {
                    "200": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/adminapi.RegisterResponse"
                                }
                            }
                        },
                        "description": "OK"
                    },
                    "401": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/adminapi.ErrorResponse"
                                }
                            }
                        },
                        "description": "Unauthorized"
                    },
                    "404": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/adminapi.ErrorResponse"
                                }
                            }
                        },
                        "description": "not set via admin api"
                    }
                },
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "summary": "Get the API-managed defaults overlay",
                "tags": [
                    "defaults"
                ]
            },
            "put": {
                "description": "Per-field overlay over the YAML defaults. Any field omitted from the body keeps its YAML value.",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "oneOf": [
                                    {
                                        "type": "object"
                                    },
                                    {
                                        "$ref": "#/components/schemas/adminapi.DefaultsRequest",
                                        "summary": "body",
                                        "description": "fields to override"
                                    }
                                ]
                            }
                        }
                    },
                    "description": "fields to override",
                    "required": true
                },
                "responses": {
                    "200": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/adminapi.RegisterResponse"
                                }
                            }
                        },
                        "description": "OK"
                    },
                    "400": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/adminapi.ErrorResponse"
                                }
                            }
                        },
                        "description": "Bad Request"
                    },
                    "401": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/adminapi.ErrorResponse"
                                }
                            }
                        },
                        "description": "Unauthorized"
                    }
                },
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "summary": "Override the defaults block",
                "tags": [
                    "defaults"
                ]
            }
        },
        "/api/v1/facts": {
            "get": {
                "responses": {
                    "200": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/adminapi.ItemListResponse"
                                }
                            }
                        },
                        "description": "OK"
                    },
                    "401": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/adminapi.ErrorResponse"
                                }
                            }
                        },
                        "description": "Unauthorized"
                    }
                },
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "summary": "List CRDT-managed facts",
                "tags": [
                    "facts"
                ]
            }
        },
        "/api/v1/facts/{name}": {
            "delete": {
                "parameters": [
                    {
                        "description": "fact name",
                        "in": "path",
                        "name": "name",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "opaque concurrency token",
                        "in": "header",
                        "name": "If-Match",
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "deleted"
                    },
                    "401": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/adminapi.ErrorResponse"
                                }
                            }
                        },
                        "description": "Unauthorized"
                    },
                    "412": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/adminapi.ErrorResponse"
                                }
                            }
                        },
                        "description": "Precondition Failed"
                    }
                },
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "summary": "Delete a fact",
                "tags": [
                    "facts"
                ]
            },
            "get": {
                "parameters": [
                    {
                        "description": "fact name",
                        "in": "path",
                        "name": "name",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/adminapi.ItemResponse"
                                }
                            }
                        },
                        "description": "OK"
                    },
                    "401": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/adminapi.ErrorResponse"
                                }
                            }
                        },
                        "description": "Unauthorized"
                    },
                    "404": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/adminapi.ErrorResponse"
                                }
                            }
                        },
                        "description": "Not Found"
                    }
                },
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "summary": "Get a single fact",
                "tags": [
                    "facts"
                ]
            },
            "put": {
                "description": "Same semantics as a YAML facts entry. URL facts spin up a fetcher on the next rebuild; the previous fetcher (if any) is stopped first.",
                "parameters": [
                    {
                        "description": "fact name",
                        "in": "path",
                        "name": "name",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "opaque concurrency token",
                        "in": "header",
                        "name": "If-Match",
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "oneOf": [
                                    {
                                        "type": "object"
                                    },
                                    {
                                        "$ref": "#/components/schemas/adminapi.FactRequest",
                                        "summary": "body",
                                        "description": "fact payload"
                                    }
                                ]
                            }
                        }
                    },
                    "description": "fact payload",
                    "required": true
                },
                "responses": {
                    "200": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/adminapi.ItemResponse"
                                }
                            }
                        },
                        "description": "OK"
                    },
                    "400": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/adminapi.ErrorResponse"
                                }
                            }
                        },
                        "description": "Bad Request"
                    },
                    "401": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/adminapi.ErrorResponse"
                                }
                            }
                        },
                        "description": "Unauthorized"
                    },
                    "412": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/adminapi.ErrorResponse"
                                }
                            }
                        },
                        "description": "Precondition Failed"
                    }
                },
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "summary": "Upsert a fact",
                "tags": [
                    "facts"
                ]
            }
        },
        "/api/v1/groups": {
            "get": {
                "description": "Returns every group currently held in the CRDT store on this node. YAML-only groups are NOT included; use GET /api/v1/config for the merged effective view.",
                "responses": {
                    "200": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/adminapi.ItemListResponse"
                                }
                            }
                        },
                        "description": "OK"
                    },
                    "401": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/adminapi.ErrorResponse"
                                }
                            }
                        },
                        "description": "missing or invalid bearer token"
                    }
                },
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "summary": "List CRDT-managed groups",
                "tags": [
                    "groups"
                ]
            }
        },
        "/api/v1/groups/{name}": {
            "delete": {
                "description": "Writes a tombstone. If a YAML group with the same name exists, it is hidden by the tombstone until the YAML entry is also removed.",
                "parameters": [
                    {
                        "description": "group name",
                        "in": "path",
                        "name": "name",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "opaque concurrency token",
                        "in": "header",
                        "name": "If-Match",
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "deleted"
                    },
                    "401": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/adminapi.ErrorResponse"
                                }
                            }
                        },
                        "description": "Unauthorized"
                    },
                    "412": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/adminapi.ErrorResponse"
                                }
                            }
                        },
                        "description": "If-Match did not match the live stamp"
                    }
                },
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "summary": "Delete a group",
                "tags": [
                    "groups"
                ]
            },
            "get": {
                "parameters": [
                    {
                        "description": "group name",
                        "in": "path",
                        "name": "name",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/adminapi.ItemResponse"
                                }
                            }
                        },
                        "description": "OK",
                        "headers": {
                            "Etag": {
                                "description": "opaque concurrency token (\\\"\u003cts\u003e-\u003cnode\u003e\\\")",
                                "schema": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "401": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/adminapi.ErrorResponse"
                                }
                            }
                        },
                        "description": "Unauthorized"
                    },
                    "404": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/adminapi.ErrorResponse"
                                }
                            }
                        },
                        "description": "Not Found"
                    }
                },
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "summary": "Get a single CRDT-managed group",
                "tags": [
                    "groups"
                ]
            },
            "put": {
                "description": "Replaces the group with the given name. The whole effective config is recompiled; if validation fails the live policy is untouched and the offending entry is pushed to the local quarantine.",
                "parameters": [
                    {
                        "description": "group name (must match body.name when present)",
                        "in": "path",
                        "name": "name",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "opaque concurrency token from a previous response",
                        "in": "header",
                        "name": "If-Match",
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "oneOf": [
                                    {
                                        "type": "object"
                                    },
                                    {
                                        "$ref": "#/components/schemas/adminapi.GroupRequest",
                                        "summary": "body",
                                        "description": "group payload, same shape as a YAML group entry"
                                    }
                                ]
                            }
                        }
                    },
                    "description": "group payload, same shape as a YAML group entry",
                    "required": true
                },
                "responses": {
                    "200": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/adminapi.ItemResponse"
                                }
                            }
                        },
                        "description": "OK",
                        "headers": {
                            "Etag": {
                                "description": "new concurrency token",
                                "schema": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "400": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/adminapi.ErrorResponse"
                                }
                            }
                        },
                        "description": "validation/compile failed; entry quarantined"
                    },
                    "401": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/adminapi.ErrorResponse"
                                }
                            }
                        },
                        "description": "Unauthorized"
                    },
                    "412": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/adminapi.ErrorResponse"
                                }
                            }
                        },
                        "description": "If-Match did not match the live stamp"
                    }
                },
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "summary": "Upsert a group",
                "tags": [
                    "groups"
                ]
            }
        },
        "/api/v1/logging": {
            "delete": {
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "401": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/adminapi.ErrorResponse"
                                }
                            }
                        },
                        "description": "Unauthorized"
                    }
                },
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "summary": "Clear the logging overlay",
                "tags": [
                    "logging"
                ]
            },
            "get": {
                "responses": {
                    "200": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/adminapi.RegisterResponse"
                                }
                            }
                        },
                        "description": "OK"
                    },
                    "401": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/adminapi.ErrorResponse"
                                }
                            }
                        },
                        "description": "Unauthorized"
                    },
                    "404": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/adminapi.ErrorResponse"
                                }
                            }
                        },
                        "description": "not set via admin api"
                    }
                },
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "summary": "Get the API-managed logging overlay",
                "tags": [
                    "logging"
                ]
            },
            "put": {
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "oneOf": [
                                    {
                                        "type": "object"
                                    },
                                    {
                                        "$ref": "#/components/schemas/adminapi.LoggingRequest",
                                        "summary": "body",
                                        "description": "fields to override"
                                    }
                                ]
                            }
                        }
                    },
                    "description": "fields to override",
                    "required": true
                },
                "responses": {
                    "200": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/adminapi.RegisterResponse"
                                }
                            }
                        },
                        "description": "OK"
                    },
                    "400": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/adminapi.ErrorResponse"
                                }
                            }
                        },
                        "description": "Bad Request"
                    },
                    "401": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/adminapi.ErrorResponse"
                                }
                            }
                        },
                        "description": "Unauthorized"
                    }
                },
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "summary": "Override the logging block",
                "tags": [
                    "logging"
                ]
            }
        },
        "/api/v1/openapi.json": {
            "get": {
                "description": "Returns the generated openapi.json. Useful for client codegen.",
                "responses": {
                    "200": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "additionalProperties": {},
                                    "type": "object"
                                }
                            }
                        },
                        "description": "OK"
                    },
                    "401": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/adminapi.ErrorResponse"
                                }
                            }
                        },
                        "description": "Unauthorized"
                    }
                },
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "summary": "OpenAPI 3.1 specification of this admin API",
                "tags": [
                    "meta"
                ]
            }
        },
        "/api/v1/quarantine": {
            "get": {
                "description": "Per-node view: each replica may legitimately quarantine different items depending on its current state. Items are re-evaluated on every rebuild.",
                "responses": {
                    "200": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/adminapi.QuarantineListResponse"
                                }
                            }
                        },
                        "description": "OK"
                    },
                    "401": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/adminapi.ErrorResponse"
                                }
                            }
                        },
                        "description": "Unauthorized"
                    }
                },
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "summary": "List quarantined CRDT entries",
                "tags": [
                    "quarantine"
                ]
            }
        },
        "/api/v1/quarantine/{section}/{name}": {
            "delete": {
                "description": "The CRDT entry itself is NOT removed (it remains the source of truth); only the local quarantine buffer is cleared for this key.",
                "parameters": [
                    {
                        "description": "groups|facts|defaults|logging",
                        "in": "path",
                        "name": "section",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "key name (empty for singleton sections)",
                        "in": "path",
                        "name": "name",
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "401": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/adminapi.ErrorResponse"
                                }
                            }
                        },
                        "description": "Unauthorized"
                    },
                    "404": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/adminapi.ErrorResponse"
                                }
                            }
                        },
                        "description": "Not Found"
                    }
                },
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "summary": "Drop a quarantined entry without retry",
                "tags": [
                    "quarantine"
                ]
            }
        }
    },
    "openapi": "3.1.0",
    "servers": [
        {
            "url": "/"
        }
    ]
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "v1",
	Title:            "request-validator admin API",
	Description:      "CRUD over the CRDT-backed sections of the policy: groups, facts, defaults, logging. The YAML loaded at boot is the floor; admin writes overlay it per-key and are gossiped to peer replicas. Every write rebuilds the effective config and either applies it atomically or quarantines the offending entry.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
